export interface FormulaDefinition {
  id: string
  name: {
    en: string
    'zh-CN': string
  }
  formulaText: {
    en: string
    'zh-CN': string
  }
  tMin: number
  tMax: number
  step: number
  scale: number
  stroke?: string
  sampler: (t: number, config?: MathBeautyProps) => { x: number, y: number }
}

export interface MathBeautyProps {
  className?: string
  debug?: boolean
  lang?: 'zh-CN' | 'en'
  effectIndex?: number
  animationSpeed?: number
  lineWidth?: number
  lineColor?: string
  axisRange?: number
  gridDensity?: number
  showGrid?: boolean
  showAxis?: boolean
  showTrail?: boolean
  trailAlpha?: number
  presetLock?: boolean
  lockOnComplete?: boolean
  modularPointCount?: number
  modularMultiplier?: number
  modularRadius?: number
  gcdLayerScale?: number
  gcdLayerRotation?: number
  quadraticResidueScale?: number
  quadraticResidueShear?: number
  gcdLatticeScale?: number
  gcdLatticeJitter?: number
  archimedeanPitch?: number
  archimedeanTwist?: number
  fermatR2Turns?: number
  fermatR2Scale?: number
  fermatR2AngularScale?: number
  implicitRange?: number
  implicitStep?: number
  implicitWaveMix?: number
  implicitSingularityGuard?: number
  implicitCrossMix?: number
  implicitExpMix?: number
  implicitNestedMix?: number
  fusionSinAmp?: number
  fusionSinFreqX?: number
  fusionSinFreqY?: number
  fusionTanMix?: number
  fusionTanFreq?: number
  fusionTanClamp?: number
  fusionFourierMix?: number
  fusionFourierHarmonics?: number
  fusionFourierDecay?: number
  oscBaseFreq?: number
  oscAmplitude?: number
  oscHarmonics?: number
  oscDecay?: number
  oscPhaseDrift?: number
  oscScanSpan?: number
  oscSinAmp?: number
  oscCosAmp?: number
  oscFreq?: number
  oscPhase?: number
  oscPhaseShift?: number
  oscOffset?: number
  implicitGcdScale?: number
  implicitBias?: number
  implicitParabolaTarget?: number
  logSpiralGrowth?: number
  logSpiralFrequency?: number
  logSpiralScale?: number
  logSpiralRadialWarp?: number
  moireBaseRadius?: number
  moireRippleAmp?: number
  moireFreqA?: number
  moireFreqB?: number
  moirePhaseDrift?: number
  innerSpiralRadius?: number
  innerSpiralTurns?: number
  innerSpiralGrowth?: number
  innerSpiralWave?: number
  innerSpiralWaveFreq?: number
  mandalaPetalCount?: number
  mandalaInnerMix?: number
  mandalaOuterMix?: number
  mandalaPhase?: number
  mandalaSharpness?: number
  fermatSpiralScale?: number
  fermatSpiralTwist?: number
  fermatSpiralMirror?: number
  cardioidScale?: number
  cardioidDistortion?: number
  limaconLoopScale?: number
  limaconOffset?: number
  bloomFrequency1?: number
  bloomFrequency2?: number
  starRosePetalCount?: number
  starRoseRadius?: number
  butterflyVariationWave?: number
  butterflyVariationExponent?: number
  ribbonOrbitAmplitude?: number
  ribbonOrbitBaseRadius?: number
  flowerWebAmplitude?: number
  flowerWebFrequency?: number
  petalChainAmplitude?: number
  petalChainFrequency?: number
  tanCotBurstScale?: number
  tanCotBurstFrequency?: number
  tanCotBurstHole?: number
  tanCotBurstCross?: number
  tanCotBurstClamp?: number
  superellipseA?: number
  superellipseB?: number
  superellipseN?: number
  pentagramBaseAmplitude?: number
  pentagramWaveAmplitude?: number
  pentagramWaveFreqX?: number
  pentagramWaveFreqY?: number
  petalOrbitAmplitude?: number
  petalOrbitFreqX?: number
  petalOrbitFreqY?: number
  petalOrbitPhase?: number
  lemniscateScale?: number
  lemniscateWarp?: number
  astroidScale?: number
  lissajousAmpX?: number
  lissajousAmpY?: number
  lissajousFreqX?: number
  lissajousFreqY?: number
  lissajousPhase?: number
  heartDepth?: number
  heartWidth?: number
  spirographR?: number
  spirographr?: number
  spirographd?: number
  hypotrochoidR?: number
  hypotrochoidr?: number
  hypotrochoidd?: number
  epicycloidR?: number
  epicycloidr?: number
  nephroidScale?: number
  trochoidRatio?: number
  trochoidOffset?: number
  trochoidPhase?: number
  juliaCRe?: number
  juliaCIm?: number
  mandelbrotBandWidth?: number
  barnsleyProbabilityJitter?: number
  chaosMode?: 'trace' | 'particles'
  chaosSystem?: 'lorenz' | 'rossler' | 'aizawa'
  chaosSteps?: number
  chaosDt?: number
  chaosScale?: number
  chaosParticleCount?: number
  chaosPhaseSpread?: number
}
